### ISSUE TITLE
Getting error in netlify

### ISSUE THREAD

**Issue by lorvent** [scottyzen/WPGridsome#2]
Hello,
I have tried using this repo in netlify, but `gridsome build` throws below error

```
$ gridsome build
6:43:10 PM: Gridsome v0.7.21
6:43:10 PM: Initializing plugins...
6:43:11 PM: Load sources - 0s
6:43:14 PM: GraphQLError: Syntax Error: Expected Name, found Int "404"
6:43:14 PM:     at syntaxError (/opt/build/repo/node_modules/graphql/error/syntaxError.js:15:10)
6:43:14 PM:     at Parser.expectToken (/opt/build/repo/node_modules/graphql/language/parser.js:1404:40)
6:43:14 PM:     at Parser.parseName (/opt/build/repo/node_modules/graphql/language/parser.js:94:22)
6:43:14 PM:     at Parser.parseObjectTypeDefinition (/opt/build/repo/node_modules/graphql/language/parser.js:795:21)
6:43:14 PM:     at Parser.parseTypeSystemDefinition (/opt/build/repo/node_modules/graphql/language/parser.js:696:23)
6:43:14 PM:     at Parser.parseDefinition (/opt/build/repo/node_modules/graphql/language/parser.js:146:23)
6:43:14 PM:     at Parser.many (/opt/build/repo/node_modules/graphql/language/parser.js:1518:26)
6:43:14 PM:     at Parser.parseDocument (/opt/build/repo/node_modules/graphql/language/parser.js:111:25)
6:43:14 PM:     at Object.parse (/opt/build/repo/node_modules/graphql/language/parser.js:36:17)
6:43:14 PM:     at Object.buildSchemaFromTypeDefinitions (/opt/build/repo/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:20:33)
6:43:14 PM:     at Object.makeExecutableSchema (/opt/build/repo/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
6:43:14 PM:     at makeRemoteExecutableSchema (/opt/build/repo/node_modules/graphql-tools/dist/stitching/makeRemoteExecutableSchema.js:139:35)
6:43:14 PM:     at GraphQLSource.getRemoteExecutableSchema (/opt/build/repo/node_modules/gridsome-source-graphql/index.js:65:12)
6:43:14 PM:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
6:43:14 PM:     at async /opt/build/repo/node_modules/gridsome-source-graphql/index.js:49:28
6:43:14 PM:     at async Plugins.run (/opt/build/repo/node_modules/gridsome/lib/app/Plugins.js:141:11)
```

i have updated URL in config file.

any help is appreciated :+1: 

thank you

**Comment by scottyzen** [comment]
Hey @lorvent 
I'm not sure what's causing the issue. If you send me your WordPress's graphql endpoint I can try run it on my machine and see if I can find the problem.

**Comment by lorvent** [comment]
Hello,
thanks for the response.

 the end point is https://www.way2fresher.com/graphql/

**Comment by scottyzen** [comment]
Hey @lorvent
I just spun up a fresh Gridsome site with just the graphql-source plugin and it wouldn't compile. So it seems the problem is with your WordPress. It looks like the graphql endpoint is empty. You might need to check if all the required plugins for WPGraphQL are installed.

**Comment by lorvent** [comment]
Hmm, i installed both WPGraphQL and ACF plugin and when i try it in playground, it is displaying data properly.

do i need to install anything other than that?

**Comment by lorvent** [comment]
I just tried playing with it in https://www.graphqlbin.com/v2/new and i am able to fetch data

URL:  https://www.way2fresher.com/graphql/

code
```
query MyQuery {
  pages {
    nodes {
      title
      slug
    }
  }
}
```

and it responded with proper json.


their site gave this code, incase you still want to try with curl
```
curl 'https://www.way2fresher.com/graphql/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: https://www.graphqlbin.com' --data-binary '{"query":"query MyQuery {\n  pages {\n    nodes {\n      title\n      slug\n    }\n  }\n}\n"}' --compressed

```

thanks.

**Comment by scottyzen** [comment]
I'm not sure why it's not connecting. The problem is on the WordPress side tho. Maybe try to manually flush your permalinks and check to see if there is a firewall blocking something.

**Comment by lorvent** [comment]
hmm, if it is a problem on WP side then it should work on above URL too right.

my doubt is.... the syntax of the output your repo expecting and what my site giving are different so there is an error.

**Comment by scottyzen** [comment]
I think the problem is on the WordPress side because I tested it with a blank Gridsome site (not this repo) with just the source-graphql plugin installed. It fails to pull in any data, so it's breaking down before it reaches any template. I've tried it with a couple of different endpoints and all the data can be seen in the GraphQL explorer.

**Comment by lorvent** [comment]
Ohh!! any idea what could be the cause?
